
server.port=8080

<<<<<<< HEAD
#the name of the route.
spring.cloud.gateway.routes[0].id=catalog           

#the destination service.
spring.cloud.gateway.routes[0].uri=http://localhost:8081         

#the predicate -> the condition that determines whether the route applies.
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/catalog/**      

#a filter applied before forwarding the request -> see comment below
=======
 #the name of the route.
spring.cloud.gateway.routes[0].id=catalog                              

#the destination service.
spring.cloud.gateway.routes[0].uri=http://localhost:8081               

 #the predicate -> the condition that determines whether the route applies.
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/catalog/**    

 #a filter applied before forwarding the request -> see comment below
>>>>>>> 8a5156a9dec728e94b47eb1d9022484037a3b7e0
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1                


# StripPrefix is a built-in Spring Cloud Gateway route filter.
# StripPrefix=1 removes the first path segment before forwarding the request.
#
# Example:
# Client request:      /api/catalog/products
# After StripPrefix:   /catalog/products
#
# This allows the gateway to expose a public API path (/api/...)
# while the backend service keeps its internal path (/catalog/...).


spring.cloud.gateway.routes[1].id=orders
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=identity
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1



